---
title: "BS_Rep_D1"
author: "Beza & Solome"
date: "2023-03-14"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readstata13)
library(ggplot2)
library(reshape2)
library(plyr)
library(margins)
library(descr)
library(sandwich)
library(pscl)
library(psych)
library(effects)
library(multiwayvcov)
library(mirt)
library(moments)
library(haven)
library(datawizard)
library(tidyverse)
#setting working directory (Beza-- be sure to comments this out and set your own when you are coding!)
knitr::opts_knit$set(root.dir = "/Users/solomonaberash/Desktop/Graduate School/SP23 STATS/Rep Paper/dataverse_files")
```


# Data Wrangling

```{r}
##Loading Both Waves of pew_ATP_W64 Data
pew_ATP_W64 <- read_dta("ATP_W64.dta")


#subetting relevant portion of wave 64
pew_ATP_W64 <- subset(pew_ATP_W64,
                      select=c(QKEY,COVID_COMFORT_a_W64,COVID_COMFORT_b_W64,
                            COVID_COMFORT_c_W64,COVID_COMFORT_d_W64,COVID_COMFORT_e_W64,
                            COVID_RESTRICTION_a_W64,COVID_RESTRICTION_b_W64,
                            COVID_RESTRICTION_c_W64,COVID_RESTRICTION_d_W64,
                            COVID_RESTRICTION_e_W64,COVID_RESTRICTION_f_W64,
                            COVID_RESTRICTION_g_W64,F_IDEO,F_PARTY_FINAL,F_SEX,
                            F_AGECAT,F_EDUCCAT2,F_MARITAL,F_INCOME,F_CREGION,
                            F_RACETHN,WEIGHT_W64))
```


## Coding and scaling ideological dependent variable (DV) 
## of interest (policy support)
```{r, eval=FALSE}
#subsetting DV data 
covid_ideo_scales <- subset(pew_ATP_W64,
                            select=c(QKEY,COVID_RESTRICTION_a_W64,COVID_RESTRICTION_b_W64,
                                     COVID_RESTRICTION_c_W64,COVID_RESTRICTION_d_W64,
                                     COVID_RESTRICTION_e_W64,COVID_RESTRICTION_f_W64,
                                     COVID_RESTRICTION_g_W64,F_IDEO))

#renaming column names of subsetted data
colnames(covid_ideo_scales) <- c("QKEY","restriction_intl_travel","restriction_most_business",
                                 "restriction_large_gatherings","restriction_sporting_events",
                                 "restriction_closing_k12","restriction_carry_out_only",
                                 "restriction_postponing_primary","libcon")

#transforming observations into characters
covid_ideo_scales[,2] <- as.character(covid_ideo_scales$restriction_intl_travel)
covid_ideo_scales[,3] <- as.character(covid_ideo_scales$restriction_most_business)
covid_ideo_scales[,4] <- as.character(covid_ideo_scales$restriction_large_gatherings)
covid_ideo_scales[,5] <- as.character(covid_ideo_scales$restriction_sporting_events)
covid_ideo_scales[,6] <- as.character(covid_ideo_scales$restriction_closing_k12)
covid_ideo_scales[,7] <- as.character(covid_ideo_scales$restriction_carry_out_only)
covid_ideo_scales[,8] <- as.character(covid_ideo_scales$restriction_postponing_primary)


#recoding observations into binary
covid_ideo_scales$restriction_intl_travel <- recode(covid_ideo_scales$restriction_intl_travel, 
                            "1"= 1, "2"= 0)  
covid_ideo_scales$restriction_most_business <- recode(covid_ideo_scales$restriction_most_business, 
                            "1"= 1, "2"= 0) 
covid_ideo_scales$restriction_large_gatherings <- recode(covid_ideo_scales$restriction_large_gatherings, 
                            "1"= 1, "2"= 0)
covid_ideo_scales$restriction_sporting_events <- recode(covid_ideo_scales$restriction_sporting_events, 
                            "1"= 1, "2"= 0) 
covid_ideo_scales$restriction_closing_k12 <- recode(covid_ideo_scales$restriction_closing_k12, 
                            "1"= 1, "2"= 0) 
covid_ideo_scales$restriction_carry_out_only <- recode(covid_ideo_scales$restriction_carry_out_only, 
                            "1"= 1, "2"= 0) 
covid_ideo_scales$restriction_postponing_primary <- recode(covid_ideo_scales$restriction_postponing_primary, 
                            "1"= 1, "2"= 0)

#recoding observations into binary
# covid_ideo_scales[covid_ideo_scales == "Necessary"] <- 1
# covid_ideo_scales[covid_ideo_scales == "Unnecessary"] <- 0

#recoding political ideology variable
# covid_ideo_scales$libcon <- ifelse(covid_ideo_scales$libcon %in% "Very Conservative",1,
#                                    ifelse(covid_ideo_scales$libcon %in% "Conservative",2,
#                                           ifelse(covid_ideo_scales$libcon %in% "Moderate",3,
#                                                  ifelse(covid_ideo_scales$libcon %in% "Liberal",4,
#                                                         ifelse(covid_ideo_scales$libcon %in% "Liberal",4,
#                                                                ifelse(covid_ideo_scales$libcon %in% "Very liberal",5,NA))))))

#transforming observations into numeric
# for(i in 2:ncol(covid_ideo_scales)){
#   covid_ideo_scales[,i] <- as.numeric(covid_ideo_scales[,i])
# }

#removing incomplete observations
covid_ideo_scales <- na.omit(covid_ideo_scales)

```


## Factor Analysis (policy support)
```{r, eval=FALSE}
library(FactoMineR)
library(factoextra)

#transforming observations into factors for factor analysis
x <- covid_ideo_scales[,c(2:9)]
# for(i in 1:8){
#   x[,i] <- as.factor(x[,i])
# }

#trying changing observations into factors the long way
x[,1] <- as.factor(covid_ideo_scales$restriction_intl_travel)
x[,2] <- as.factor(covid_ideo_scales$restriction_most_business)
x[,3] <- as.factor(covid_ideo_scales$restriction_large_gatherings)
x[,4] <- as.factor(covid_ideo_scales$restriction_sporting_events)
x[,5] <- as.factor(covid_ideo_scales$restriction_closing_k12)
x[,6] <- as.factor(covid_ideo_scales$restriction_carry_out_only)
x[,7] <- as.factor(covid_ideo_scales$restriction_postponing_primary)
#x[,8] <- as.factor(covid_ideo_scales$libcon)
#x

#conducting exploratory factor analysis & plotting results
factanal <- FAMD(x, graph = F,ncp=7,sup.var = NULL)
library(rstatix)

fviz_screeplot(factanal)
fviz_contrib(factanal, "var", axes = 1)
fviz_contrib(factanal, "var", axes = 2)
fviz_contrib(factanal, "var", axes = 3)
fviz_famd_var(factanal, "var", repel = TRUE, col.var = "black")

factanal <- fa(covid_ideo_scales[,c(2:9)], nfactors=2, rotate="promax", fm="pa")
scores <- data.frame(factanal$scores)
loadings(factanal)
loadings <- factanal$loadings
loadings <- data.frame(f1 = loadings[,1],f2=loadings[,2])

plot(factanal$loadings,type="n") # set up plot 
text(factanal$loadings,labels=names(covid_ideo_scales)[2:9],cex=.7) # add variable names

library(ggrepel)

alpha(covid_ideo_scales[,c(2:9)])

library(grid)
library(gridExtra)
loadings$vars <- ifelse(rownames(loadings) %in% "restriction_intl_travel","International Travel",
                        ifelse(rownames(loadings) %in% "restriction_most_business","Most Businesses",
                               ifelse(rownames(loadings) %in% "restriction_large_gatherings","Large Gatherings",
                                      ifelse(rownames(loadings) %in% "restriction_sporting_events","Sporting Events",
                                             ifelse(rownames(loadings) %in% "restriction_closing_k12","K-12 Schools",
                                                    ifelse(rownames(loadings) %in% "restriction_carry_out_only","Carry-out Only",
                                                           ifelse(rownames(loadings) %in% "restriction_postponing_primary","Postponing Primary",
                                                                  ifelse(rownames(loadings) %in% "libcon","Left-Right Ideology",NA))))))))

#plotting factor analysis plot
plot <- ggplot(loadings,aes(x = f1, y=f2,label=vars)) + 
  theme_minimal() + 
  geom_label_repel() + 
  scale_x_continuous("First Dimension Factor (Proportion of Variance: 36%)") + 
  scale_y_continuous("Second Dimension Factor (Propoportion of Variance 4%)") + 
  geom_segment(aes(x = 0,y = 0,xend = f1,yend = f2),arrow=arrow()) 

grid.newpage()
footnote <- expression("Cronbach's Standardized"~alpha~"="~0.78)
g <- arrangeGrob(plot, 
                 bottom = textGrob(footnote, x = 0.025, hjust = 0, vjust= 0, 
                                   y=0.75, gp = gpar(fontface = "italic", 
                                                     fontsize = 9, col = "black")))
grid.draw(g)
ggsave(file="factor_analysis_covid19_policies.png", g, width = 8, height = 5.43, units = "in")

covid_ideo_scales <- cbind(covid_ideo_scales,scores)
colnames(covid_ideo_scales)[10:11] <- c("covid_restriction_fa_dim1","covid_restriction_fa_dim2")
covid_ideo_scales$summated_restriction_scale <- rowSums(covid_ideo_scales[2:8],na.rm=T)
```


## Item-Response Theory Model 
```{r, eval=F}
irt <- mirt(covid_ideo_scales[2:8], model = 1, itemtype = "graded", SE = T, verbose = T,removeEmptyRows = TRUE)
plt <- plot(irt, type = 'trace', facet_items=F) #store the object
print(plt) #plot the object
str(plt) #find the data
pltdata <- data.frame(lapply(plt$panel.args, function(x) do.call(cbind, x))[[1]])

groups <- plot(irt, type = 'trace', facet_items=T)
groups$packet.sizes
pltdata$item <- rep(colnames(covid_ideo_scales)[2:8], each = 200)
pltdata$response <- groups$panel.args.common$groups

plt$panel.args.common$groups

pltdata$item2 <- factor(pltdata$item,levels=c("restriction_carry_out_only","restriction_closing_k12","restriction_intl_travel","restriction_large_gatherings","restriction_most_business","restriction_postponing_primary","restriction_sporting_events"),labels=c("Carry Out Only","Close K-12 Schools","Restrict Intl. Travel","Restrict Large Gatherings","Restrict Most Businesses","Postpone Primary Elections","Restrict Sporting Events"))

pltdata$item2 <- factor(pltdata$item2,levels=c("Restrict Intl. Travel","Restrict Sporting Events","Close K-12 Schools","Restrict Large Gatherings","Carry Out Only","Restrict Most Businesses","Postpone Primary Elections"))

plot <- ggplot(pltdata, aes(x, y,linetype=item2,color=item2)) + geom_line() + scale_x_continuous(expression(theta)) + scale_y_continuous("Pr (Support)") + geom_hline(aes(yintercept = 0.5))  + theme_minimal() + labs(color="Policy",linetype="Policy") + theme(legend.position="bottom") #+ scale_colour_grey(start = 0, end = .5) + ggtitle("Ordinal IRT Model Characteric Curves for Emphatic Racism Scale")
#ggsave(file="covid19_restrictions_irt_curves_probs.png", plot, width = 8, height = 5.43, units = "in")
```

## Scores
```{r, eval=F}
covid_ideo_scales$covid_restriction_fa_dim2 <- fscores(irt, full.scores = TRUE, full.scores.SE = F)
colnames(covid_ideo_scales)[11] <- "covid_restriction_irt"

pew_ATP_W64_ATP_W64 <- merge(pew_ATP_W64_ATP_W64,covid_ideo_scales,by=c("QKEY"),all=T)
pew_ATP_W64_ATP_W64$covid_restriction_fa_dim1 <- pew_ATP_W64_ATP_W64$covid_restriction_fa_dim1-mean(pew_ATP_W64_ATP_W64$covid_restriction_fa_dim1,na.rm=T)
```

## Covariates
```{r, eval=F}
#transforming gender covariate & plotting
pew_ATP_W64$female <- as.character(pew_ATP_W64$F_SEX)
pew_ATP_W64$female <- factor(pew_ATP_W64$female,levels=c("Male","Female"))

ggplot(na.omit(pew_ATP_W64),aes(x=female,y=covid_restriction_fa_dim1)) + geom_boxplot()

#transforming political identification & using to create weights
pew_ATP_W64$pid3 <- as.character(pew_ATP_W64$F_PARTY_FINAL)
pew_ATP_W64$pid3 <- factor(pew_ATP_W64$pid3,levels=c("Republican","Independent","Democrat"))

pew_ATP_W64$weight <- as.numeric(pew_ATP_W64$WEIGHT_W64)

#transforming & cleaning age covariate
pew_ATP_W64$age_linear <- as.numeric(factor(pew_ATP_W64$F_AGECAT))
pew_ATP_W64$age_linear[pew_ATP_W64$age_linear %in% 5] <- NA # Get rid of refused

#transforming & cleaning education covariate
pew_ATP_W64$educ_linear <- as.numeric(factor(pew_ATP_W64$F_EDUCCAT2))
pew_ATP_W64$educ_linear[pew_ATP_W64$educ_linear %in% 7] <- NA # Get rid of refused

#transforming & cleaning marital covariate
pew_ATP_W64$marital_status <- ifelse(pew_ATP_W64$F_MARITAL %in% "Married",1,0)
pew_ATP_W64$marital_status[pew_ATP_W64$F_MARITAL %in% "Refused"] <- NA # Get rid of refused

#transforming & cleaning income covariate
pew_ATP_W64$income_linear <- as.numeric(factor(pew_ATP_W64$F_INCOME))
pew_ATP_W64$income_linear[pew_ATP_W64$income_linear %in% 10] <- NA # Get rid of refused

#transforming & cleaning region & white race covariates
pew_ATP_W64$region_factor <- pew_ATP_W64$F_CREGION
pew_ATP_W64$white_respondent <- ifelse(pew_ATP_W64$F_RACETHN %in% "White non-Hispanic",1,0)
pew_ATP_W64$white_respondent[pew_ATP_W64$F_RACETHN %in% "Refused"] <- NA # Get rid of refused

#getting other race covariate
hold <- read_dta("ATP_W42.dta")
hold <- hold[,c("QKEY", "F_RACECMB")]

pew_ATP_W64 <- merge(pew_ATP_W64,hold,by=c("QKEY"),all=T)

pew_ATP_W64$race3 <- ifelse(pew_ATP_W64$F_RACETHN %in% "White non-Hispanic","white",ifelse(pew_ATP_W64$F_RACETHN %in% "Black non-Hispanic","black",ifelse(pew_ATP_W64$F_RACETHN %in% "Hispanic","hispanic",NA)))
pew_ATP_W64$race3 <- ifelse(is.na(pew_ATP_W64$race3) & pew_ATP_W64$F_RACECMB %in% "Asian or Asian-American","asian",pew_ATP_W64$race3)

pew_ATP_W64$race3 <- factor(pew_ATP_W64$race3,levels=c("white","black","hispanic","asian"))
```



## Trust
```{r, eval=F}
#loading trust data from wave 42
trust <- read_dta("ATP_W42.dta")
trust <- subset(trust,select=c("QKEY","CONFa_W42","CONFb_W42","CONFd_F1_W42","CONFd_F2_W42", "POLICY1_W42","POLICY2_W42","POLICY3_W42","SCM2_W42","SCM3_W42","SCM4a_W42","SCM4b_W42"))

colnames(trust) <- c("QKEY","trust_elected_officials","trust_media",
                     "trust_medial_scientists","trust_scientists",
                     "scientists_active_role_policy","scientists_pivotal_policy",
                     "scientists_better_policy","scientific_method",
                     "scientists_judgement_facts","research_essential_immediate_applications",
                     "research_essential_advance_knowledge")

#omitting non-responses 
trust[trust == "Refused"] <- NA

for(i in 2:ncol(trust)){
  print(table(trust[,i]))
  print(levels(trust[,i]))
}
for(i in 2:ncol(trust)){
  trust[,i] <- as.character(trust[,i])
  print(table(trust[,i]))
}

#recoding responses to each trust survey question
trust[trust == "Essential"] <- 4
trust[trust == "Important, but not essential"] <- 3
trust[trust == "Not too important"] <- 2
trust[trust == "Not important at all"] <- 1

trust[trust == "A great deal of confidence"] <- 4
trust[trust == "A fair amount of confidence"] <- 3
trust[trust == "Not too much confidence"] <- 2
trust[trust == "No confidence at all"] <- 1

trust[trust == "Scientists should take an active role in public policy debates about scientific issues"] <- 2
trust[trust == "Scientists should focus on establishing sound scientific facts and stay out of public policy debates"] <- 1

trust[trust == "Public opinion should NOT play an important role to guide policy decisions about scientific issues because these issues"] <- 2
trust[trust == "Public opinion should play an important role to guide policy decisions about scientific issues"] <- 1

trust[trust == "Usually BETTER at making good policy decisions about scientific issues than other people"] <- 3
trust[trust == "NEITHER BETTER NOR WORSE at making good policy decisions about scientific issues than other people"] <- 2
trust[trust == "Usually WORSE at making good policy decisions about scientific issues than other people"] <- 1

trust[trust == "The scientific method generally produces accurate conclusions"] <- 2
trust[trust == "The scientific method can be used to produce any conclusion the researcher wants"] <- 1

trust[trust == "Scientists make judgments based solely on the facts"] <- 2
trust[trust == "Scientists' judgments are just as likely to be biased as other people's"] <- 1

trust$trust_scientists <- ifelse(is.na(trust$trust_medial_scientists),trust$trust_scientists,
                                 ifelse(is.na(trust$trust_scientists),trust$trust_medial_scientists,NA))

trust$trust_medial_scientists <- NULL
trust$scientists_pivotal_policy <- NULL

for(i in 2:ncol(trust)){
  trust[,i] <- as.numeric(trust[,i])
  print(table(trust[,i]))
}  

factanal <- fa(trust[,c(4:10)], nfactors=2, rotate="promax", fm="pa")
scores <- data.frame(factanal$scores)
loadings(factanal)
loadings <- factanal$loadings
loadings <- data.frame(f1 = loadings[,1],f2=loadings[,2])

plot(factanal$loadings,type="n") # set up plot 
text(factanal$loadings,labels=names(trust)[4:10],cex=.7) # add variable names

library(ggrepel)

alpha(trust[,c(4:8)])
skewness(loadings$f1, na.rm=T)
kurtosis(loadings$f1, na.rm=T)

alpha(trust[,c(9:10)])
skewness(loadings$f2, na.rm=T)
kurtosis(loadings$f2, na.rm=T)

loadings$vars <- ifelse(rownames(loadings) %in% "trust_scientists","Trust Scientists",ifelse(rownames(loadings) %in% "scientists_active_role_policy","Scientists Active Role Policy",ifelse(rownames(loadings) %in% "scientists_pivotal_policy","PO Guiding Policy Science",ifelse(rownames(loadings) %in% "scientists_better_policy","Scientists Better Policymakers",ifelse(rownames(loadings) %in% "scientific_method","Scientific Method Validity",ifelse(rownames(loadings) %in% "scientists_judgement_facts","Unbiased Scientists",ifelse(rownames(loadings) %in% "research_essential_immediate_applications","Research Essential Applications",ifelse(rownames(loadings) %in% "research_essential_advance_knowledge","Research Essential Knowledge",NA))))))))

plot <- ggplot(loadings,aes(x = f1, y=f2,label=vars)) + theme_minimal() + geom_label_repel() + scale_x_continuous("First Dimension Factor") + scale_y_continuous("Second Dimension Factor") + geom_segment(aes(x = 0,y = 0,xend = f1,yend = f2),arrow=arrow())  # (Proportion of Variance F1: 18%) (Propoportion of F2 Variance 16%)"
grid.newpage()
footnote <- expression("Cronbach's Standardized"~alpha~"="~0.66)
g <- arrangeGrob(plot, bottom = textGrob(footnote, x = 0.025, hjust = 0, vjust= 0, y=0.75, gp = gpar(fontface = "italic", fontsize = 9, col = "black")))
grid.draw(g)
#ggsave(file="factor_analysis_scientific_trust.png", g, width = 8, height = 5.43, units = "in")

trust <- cbind(trust,scores)
colnames(trust)[11:12] <- c("trust_scientists_fa_dim1","trust_scientists_fa_dim2")

pew_ATP_W64 <- merge(pew_ATP_W64,trust,by=c("QKEY"),all=T)

x <- subset(pew_ATP_W64,select=c(pid3,trust_scientists_fa_dim1,trust_scientists_fa_dim2))
x <- na.omit(x)
x$pid <- ifelse(x$pid3 %in% "Democrat","D",ifelse(x$pid3 %in% "Republican","R",ifelse(x$pid3 %in% "Independent","I",NA)))

plot <- ggplot(x,aes(x=trust_scientists_fa_dim1,y=trust_scientists_fa_dim2,label=pid,color=pid)) + geom_text(alpha=0.2) + scale_color_manual("",values=c("blue","purple","red"))

x1 <- x
x1$pid3 <- "Full Sample"
x <- rbind(x,x1)
x$pid3 <- factor(x$pid3,levels=c("Republican","Independent","Democrat","Full Sample"),labels=c("Republican Partisans","Independent Partisans","Democratic Partisans","Full Sample"))

print(summary(aov(trust_scientists_fa_dim1 ~ pid3, data = x)))

plot <- ggplot(x, aes(x=pid3,y=trust_scientists_fa_dim1, group=pid3,fill=pid3)) + geom_boxplot(alpha=0.2) + theme_minimal() + scale_y_continuous("Latent Scientific Trust") + scale_x_discrete("") + scale_fill_manual("",values=c("red","purple","blue","black")) + theme(legend.position = "none") 
#ggsave(file="scientific_trust_boxplots_by_party.png", plot, width = 8, height = 5.43, units = "in")
```

# Data Analysis: COVID Policy ~ Scientific Trust: Baseline Effects

## Baseline Trust Effects
```{r, eval=FALSE}
baseline_trust_effects <- list()
for(i in which(colnames(pew) == "restriction_intl_travel"):which(colnames(pew) == "restriction_postponing_primary")){
  summary(model <- glm(pew[,i] ~ trust_scientists_fa_dim1 + trust_media + trust_elected_officials + female + pid3 + libcon + age_linear + educ_linear + income_linear + race3 + region_factor, data=pew, weights=weight, family = binomial(link = "logit")))
  mes <- summary(margins(model, variables=c("trust_scientists_fa_dim1","trust_media","trust_elected_officials"), type="response", change="minmax"))
  mes$model <- colnames(pew)[i]
  mes$category <- "Full Sample Baseline"
  baseline_trust_effects[[i]] <- mes
}
baseline_trust_effects <- ldply(baseline_trust_effects,data.frame)

baseline_trust_effects$pid3 <- "Full Baseline Sample"
baseline_trust_effects$category <- NULL

effects <- baseline_trust_effects
effects$ylo90 <- (effects$AME - (qt(.95, 100) * effects$SE))
effects$yhi90 <- (effects$AME + (qt(.95, 100) * effects$SE))
effects$model2 <- ifelse(effects$model %in% "restriction_carry_out_only","Dependent Variable: Restaurants Carry Out Only",
                         ifelse(effects$model %in% "restriction_closing_k12","Dependent Variable: Close K-12 Schools",
                                ifelse(effects$model %in% "restriction_intl_travel","Dependent Variable: Restrict International Travel",
                                       ifelse(effects$model %in% "restriction_large_gatherings","Dependent Variable: Restrict Large Gatherings",
                                              ifelse(effects$model %in% "restriction_most_business","Dependent Variable: Restrict Most Businesses",
                                                     ifelse(effects$model %in% "restriction_postponing_primary","Dependent Variable: Postpone Primary Elections",
                                                            ifelse(effects$model %in% "restriction_sporting_events","Dependent Variable: Restrict Sporting Events",NA)))))))

effects$factor <- ifelse(effects$factor %in% "trust_elected_officials","Elected Officials Trust",
                         ifelse(effects$factor %in% "trust_media","Media Trust",
                                ifelse(effects$factor %in% "trust_scientists_fa_dim1","Scientific Trust",NA)))

effects$label <- ifelse(effects$p < 0.01,paste(round(effects$AME,2),"***",sep=""),ifelse(effects$p < 0.05,paste(round(effects$AME,2),"**",sep=""),ifelse(effects$p < 0.10,paste(round(effects$AME,2),"*",sep=""),NA)))

for(i in unique(effects$model)){
  x <- subset(effects,effects$model %in% i)
  plot <- ggplot(x,aes(x=factor,y=AME,factor=factor,group=factor,color=factor,shape=factor,label=label,fill=factor)) + facet_wrap(~model2) + coord_flip() + geom_linerange(aes(x= factor, ymin = ylo90, ymax = yhi90), position = position_dodge(width=0.75), lwd  = 1) + geom_pointrange(aes(x= factor, ymin = lower, ymax = upper), lwd = 1/2, position = position_dodge(width=0.75),fill="white") + theme_minimal() + scale_x_discrete("") + scale_y_continuous("Min/Max First Difference Marginal Effects on Pr(Necessary Government Policy)") + geom_hline(yintercept = 0, colour = gray(1/2), lty = 2) +  labs(color="Trust Effects",shape="Trust Effects") + theme(legend.position = "none") + theme(axis.text.x = element_text(hjust = 0.5),axis.text.y = element_text(hjust = 0.5)) + geom_label(vjust=-0.5,hjust=0.25,fill="white") + labs(caption="* p < 0.1; ** p < 0.05; *** p < 0.01") + scale_shape_manual("",values=c(23,22,21))
  print(plot)
  #ggsave(file=paste(i,"_model",".png",sep=""), plot, width = 8, height = 5.43, units = "in")
}
```




